version: 2.1

executors:
  dotnet-executor:
    docker:
      
image: mcr.microsoft.com/dotnet/sdk:6.0 # Adjust to your .NET version
  working_directory: ~/repo

jobs:
  sonar_scan:
    executor: dotnet-executor
    steps:
      
checkout
run:
      name: Install Dependencies
      command: dotnet restore
run:
    name: Build Project
    command: dotnet build
run:
  name: Install SonarScanner for .NET
  command: dotnet tool install --global dotnet-sonarscanner

workflows:
  version: 2
  sonar_workflow:
    jobs:
      
sonar_scan
